import type { CrmState } from "./types"
import { EMPTY_TOUCHPOINTS, type LeadTouchpoints } from "./scoring"

export const ORG = {
  name: "Helios Industrial",
  workspace: "Meridian",
  zohoOrg: "helios_eu_prod",
  apiVersion: "v8",
  region: "EU (zoho.eu)",
  quarter: "Q3 2026",
  quota: 4_200_000,
}

const rawSeed = {
  currentUserId: "usr_elena",
  users: [
    {
      id: "usr_elena",
      name: "Elena Voss",
      email: "elena.voss@helios.ind",
      role: "VP Sales",
      territory: "EMEA",
      avatarHue: 28,
      quota: 4_200_000,
    },
    {
      id: "usr_marcus",
      name: "Marcus Chen",
      email: "marcus.chen@helios.ind",
      role: "Enterprise AE",
      territory: "DACH & Benelux",
      avatarHue: 162,
      quota: 1_800_000,
    },
    {
      id: "usr_priya",
      name: "Priya Nair",
      email: "priya.nair@helios.ind",
      role: "Mid-Market AE",
      territory: "UK & Nordics",
      avatarHue: 210,
      quota: 1_100_000,
    },
    {
      id: "usr_jonah",
      name: "Jonah Hale",
      email: "jonah.hale@helios.ind",
      role: "SDR",
      territory: "Inbound EMEA",
      avatarHue: 48,
      quota: 240_000,
    },
    {
      id: "usr_amira",
      name: "Amira Soltani",
      email: "amira.soltani@helios.ind",
      role: "Solutions Consultant",
      territory: "Enterprise",
      avatarHue: 330,
      quota: 0,
    },
    {
      id: "usr_theo",
      name: "Theo Brandt",
      email: "theo.brandt@helios.ind",
      role: "CSM",
      territory: "Installed Base",
      avatarHue: 120,
      quota: 620_000,
    },
  ],
  accounts: [
    {
      id: "acc_rhinegrid",
      name: "RhineGrid AG",
      industry: "Utilities",
      type: "Customer",
      website: "rhinegrid.de",
      phone: "+49 211 440 1900",
      billingCity: "Düsseldorf",
      billingCountry: "Germany",
      annualRevenue: 2_140_000_000,
      employees: 8600,
      ownerId: "usr_marcus",
      rating: "Hot",
      description:
        "Transmission operator covering the Lower Rhine. Expanding CHP and heat-recovery across 14 substations.",
      createdTime: "2024-11-03T09:12:00.000Z",
    },
    {
      id: "acc_pacific",
      name: "Pacific Foundry",
      industry: "Manufacturing",
      type: "Prospect",
      website: "pacificfoundry.com",
      phone: "+1 503 555 0188",
      billingCity: "Portland",
      billingCountry: "United States",
      annualRevenue: 480_000_000,
      employees: 1900,
      ownerId: "usr_marcus",
      rating: "Hot",
      description:
        "Specialty steel caster. Board approved a 2026 energy intensity reduction of 18%.",
      createdTime: "2026-04-18T15:40:00.000Z",
    },
    {
      id: "acc_nordhavn",
      name: "Nordhavn Shipping",
      industry: "Logistics",
      type: "Prospect",
      website: "nordhavn.dk",
      phone: "+45 33 12 90 40",
      billingCity: "Copenhagen",
      billingCountry: "Denmark",
      annualRevenue: 910_000_000,
      employees: 3200,
      ownerId: "usr_priya",
      rating: "Warm",
      description:
        "Ro-ro and short-sea operator. Shore-power and terminal heat recovery RFP in market.",
      createdTime: "2026-05-02T11:05:00.000Z",
    },
    {
      id: "acc_atlas",
      name: "Atlas Cement Iberia",
      industry: "Materials",
      type: "Prospect",
      website: "atlascement.es",
      phone: "+34 93 414 2200",
      billingCity: "Barcelona",
      billingCountry: "Spain",
      annualRevenue: 1_050_000_000,
      employees: 4100,
      ownerId: "usr_marcus",
      rating: "Warm",
      description: "Three kiln lines. Waste-heat recovery is the 2026 capex priority.",
      createdTime: "2026-03-21T08:22:00.000Z",
    },
    {
      id: "acc_kepler",
      name: "Kepler MedTech",
      industry: "Healthcare",
      type: "Customer",
      website: "keplermed.tech",
      phone: "+1 617 555 0144",
      billingCity: "Boston",
      billingCountry: "United States",
      annualRevenue: 260_000_000,
      employees: 740,
      ownerId: "usr_theo",
      rating: "Warm",
      description: "Device campus with dual-feed power. Backup CHP installed in June.",
      createdTime: "2025-08-14T13:00:00.000Z",
    },
    {
      id: "acc_vossmann",
      name: "Vossmann Food Group",
      industry: "Food & Beverage",
      type: "Prospect",
      website: "vossmann.de",
      phone: "+49 89 770 4410",
      billingCity: "Munich",
      billingCountry: "Germany",
      annualRevenue: 640_000_000,
      employees: 2800,
      ownerId: "usr_priya",
      rating: "Hot",
      description: "Cold-chain energy program across six plants. CFO is the economic buyer.",
      createdTime: "2026-06-09T10:18:00.000Z",
    },
    {
      id: "acc_lumen",
      name: "Lumen Rail",
      industry: "Transportation",
      type: "Prospect",
      website: "lumenrail.co.uk",
      phone: "+44 161 555 0190",
      billingCity: "Manchester",
      billingCountry: "United Kingdom",
      annualRevenue: 390_000_000,
      employees: 1500,
      ownerId: "usr_priya",
      rating: "Cold",
      description: "Regional freight. Evaluating traction-substation heat recapture.",
      createdTime: "2026-07-01T16:44:00.000Z",
    },
    {
      id: "acc_sable",
      name: "Sable Mining PLC",
      industry: "Mining",
      type: "Prospect",
      website: "sablemining.com",
      phone: "+27 11 555 0271",
      billingCity: "Johannesburg",
      billingCountry: "South Africa",
      annualRevenue: 1_720_000_000,
      employees: 9200,
      ownerId: "usr_marcus",
      rating: "Warm",
      description: "Off-grid plant considering a 24MW microgrid with CHP and storage.",
      createdTime: "2026-02-11T07:55:00.000Z",
    },
    {
      id: "acc_oriole",
      name: "Oriole Data Centers",
      industry: "Technology",
      type: "Customer",
      website: "orioledc.nl",
      phone: "+31 20 555 0330",
      billingCity: "Amsterdam",
      billingCountry: "Netherlands",
      annualRevenue: 310_000_000,
      employees: 420,
      ownerId: "usr_theo",
      rating: "Hot",
      description: "Three AMS campuses. Heat reuse to district network went live in August.",
      createdTime: "2025-01-20T09:30:00.000Z",
    },
    {
      id: "acc_fenwick",
      name: "Fenwick Glassworks",
      industry: "Manufacturing",
      type: "Prospect",
      website: "fenwickglass.fr",
      phone: "+33 4 72 555 019",
      billingCity: "Lyon",
      billingCountry: "France",
      annualRevenue: 175_000_000,
      employees: 680,
      ownerId: "usr_priya",
      rating: "Warm",
      description: "Furnace waste-heat project tied to 2027 ESG bond covenants.",
      createdTime: "2026-07-22T12:10:00.000Z",
    },
  ],
  contacts: [
    {
      id: "con_lena",
      firstName: "Lena",
      lastName: "Krüger",
      title: "Head of Energy Procurement",
      email: "lena.krueger@rhinegrid.de",
      phone: "+49 211 440 1944",
      accountId: "acc_rhinegrid",
      ownerId: "usr_marcus",
      department: "Procurement",
      mailingCity: "Düsseldorf",
      mailingCountry: "Germany",
      createdTime: "2024-11-03T09:20:00.000Z",
    },
    {
      id: "con_stefan",
      firstName: "Stefan",
      lastName: "Vogel",
      title: "CTO",
      email: "stefan.vogel@rhinegrid.de",
      phone: "+49 211 440 1911",
      accountId: "acc_rhinegrid",
      ownerId: "usr_marcus",
      department: "Engineering",
      mailingCity: "Düsseldorf",
      mailingCountry: "Germany",
      createdTime: "2025-02-14T11:00:00.000Z",
    },
    {
      id: "con_owen",
      firstName: "Owen",
      lastName: "Blake",
      title: "VP Operations",
      email: "owen.blake@pacificfoundry.com",
      phone: "+1 503 555 0191",
      accountId: "acc_pacific",
      ownerId: "usr_marcus",
      department: "Operations",
      mailingCity: "Portland",
      mailingCountry: "United States",
      createdTime: "2026-04-18T15:50:00.000Z",
    },
    {
      id: "con_freja",
      firstName: "Freja",
      lastName: "Holm",
      title: "Director of Sustainability",
      email: "freja.holm@nordhavn.dk",
      phone: "+45 33 12 90 55",
      accountId: "acc_nordhavn",
      ownerId: "usr_priya",
      department: "ESG",
      mailingCity: "Copenhagen",
      mailingCountry: "Denmark",
      createdTime: "2026-05-02T11:12:00.000Z",
    },
    {
      id: "con_mateo",
      firstName: "Mateo",
      lastName: "Ruiz",
      title: "Plant Director",
      email: "mateo.ruiz@atlascement.es",
      phone: "+34 93 414 2218",
      accountId: "acc_atlas",
      ownerId: "usr_marcus",
      department: "Operations",
      mailingCity: "Barcelona",
      mailingCountry: "Spain",
      createdTime: "2026-03-21T08:40:00.000Z",
    },
    {
      id: "con_hannah",
      firstName: "Hannah",
      lastName: "Cole",
      title: "Facilities Director",
      email: "hannah.cole@keplermed.tech",
      phone: "+1 617 555 0170",
      accountId: "acc_kepler",
      ownerId: "usr_theo",
      department: "Facilities",
      mailingCity: "Boston",
      mailingCountry: "United States",
      createdTime: "2025-08-14T13:20:00.000Z",
    },
    {
      id: "con_annika",
      firstName: "Annika",
      lastName: "Berg",
      title: "CFO",
      email: "annika.berg@vossmann.de",
      phone: "+49 89 770 4422",
      accountId: "acc_vossmann",
      ownerId: "usr_priya",
      department: "Finance",
      mailingCity: "Munich",
      mailingCountry: "Germany",
      createdTime: "2026-06-09T10:30:00.000Z",
    },
    {
      id: "con_callum",
      firstName: "Callum",
      lastName: "Reeves",
      title: "Head of Infrastructure",
      email: "callum.reeves@lumenrail.co.uk",
      phone: "+44 161 555 0194",
      accountId: "acc_lumen",
      ownerId: "usr_priya",
      department: "Infrastructure",
      mailingCity: "Manchester",
      mailingCountry: "United Kingdom",
      createdTime: "2026-07-01T16:50:00.000Z",
    },
    {
      id: "con_thabo",
      firstName: "Thabo",
      lastName: "Mokoena",
      title: "GM, Energy Systems",
      email: "thabo.mokoena@sablemining.com",
      phone: "+27 11 555 0280",
      accountId: "acc_sable",
      ownerId: "usr_marcus",
      department: "Energy",
      mailingCity: "Johannesburg",
      mailingCountry: "South Africa",
      createdTime: "2026-02-11T08:10:00.000Z",
    },
    {
      id: "con_iris",
      firstName: "Iris",
      lastName: "de Vries",
      title: "VP, Campus Engineering",
      email: "iris.devries@orioledc.nl",
      phone: "+31 20 555 0338",
      accountId: "acc_oriole",
      ownerId: "usr_theo",
      department: "Engineering",
      mailingCity: "Amsterdam",
      mailingCountry: "Netherlands",
      createdTime: "2025-01-20T09:44:00.000Z",
    },
    {
      id: "con_luc",
      firstName: "Luc",
      lastName: "Morel",
      title: "Technical Director",
      email: "luc.morel@fenwickglass.fr",
      phone: "+33 4 72 555 027",
      accountId: "acc_fenwick",
      ownerId: "usr_priya",
      department: "Engineering",
      mailingCity: "Lyon",
      mailingCountry: "France",
      createdTime: "2026-07-22T12:22:00.000Z",
    },
    {
      id: "con_nora",
      firstName: "Nora",
      lastName: "Lindqvist",
      title: "Procurement Lead",
      email: "nora.lindqvist@nordhavn.dk",
      phone: "+45 33 12 90 61",
      accountId: "acc_nordhavn",
      ownerId: "usr_priya",
      department: "Procurement",
      mailingCity: "Copenhagen",
      mailingCountry: "Denmark",
      createdTime: "2026-06-18T09:00:00.000Z",
    },
  ],
  leads: [
    {
      id: "led_sabine",
      firstName: "Sabine",
      lastName: "Keller",
      company: "Alpine Grid Services",
      title: "Program Manager",
      email: "sabine.keller@alpinegrid.ch",
      phone: "+41 44 555 0182",
      status: "Hot",
      source: "Website",
      industry: "Utilities",
      annualRevenue: 220_000_000,
      rating: "Hot",
      ownerId: "usr_jonah",
      score: 92,
      city: "Zurich",
      country: "Switzerland",
      createdTime: "2026-08-28T07:14:00.000Z",
      converted: false,
    },
    {
      id: "led_rafael",
      firstName: "Rafael",
      lastName: "Costa",
      company: "Iberia Cold Logistics",
      title: "COO",
      email: "rafael.costa@iberiacold.es",
      phone: "+34 91 555 0440",
      status: "Qualified",
      source: "Trade Show",
      industry: "Logistics",
      annualRevenue: 95_000_000,
      rating: "Warm",
      ownerId: "usr_jonah",
      score: 78,
      city: "Madrid",
      country: "Spain",
      createdTime: "2026-08-12T16:02:00.000Z",
      converted: false,
    },
    {
      id: "led_mei",
      firstName: "Mei",
      lastName: "Tan",
      company: "Harbourline Terminals",
      title: "Head of Assets",
      email: "mei.tan@harbourline.sg",
      phone: "+65 6555 0199",
      status: "Contacted",
      source: "Outbound",
      industry: "Logistics",
      annualRevenue: 410_000_000,
      rating: "Warm",
      ownerId: "usr_jonah",
      score: 64,
      city: "Singapore",
      country: "Singapore",
      createdTime: "2026-09-01T04:40:00.000Z",
      converted: false,
    },
    {
      id: "led_dario",
      firstName: "Dario",
      lastName: "Esposito",
      company: "Vesuvio Ceramics",
      title: "Plant Manager",
      email: "dario.esposito@vesuvioceramics.it",
      phone: "+39 081 555 0133",
      status: "Not Contacted",
      source: "Inbound Call",
      industry: "Manufacturing",
      annualRevenue: 48_000_000,
      rating: "Cold",
      ownerId: "usr_jonah",
      score: 41,
      city: "Naples",
      country: "Italy",
      createdTime: "2026-09-08T13:25:00.000Z",
      converted: false,
    },
    {
      id: "led_ines",
      firstName: "Inès",
      lastName: "Bernard",
      company: "Loire BioPharma",
      title: "EHS Director",
      email: "ines.bernard@loirebio.fr",
      phone: "+33 2 40 555 011",
      status: "Hot",
      source: "Referral",
      industry: "Healthcare",
      annualRevenue: 180_000_000,
      rating: "Hot",
      ownerId: "usr_priya",
      score: 88,
      city: "Nantes",
      country: "France",
      createdTime: "2026-08-21T09:48:00.000Z",
      converted: false,
    },
    {
      id: "led_harun",
      firstName: "Harun",
      lastName: "Yılmaz",
      company: "Anatolia Steel",
      title: "Energy Manager",
      email: "harun.yilmaz@anatoliasteel.com",
      phone: "+90 212 555 0177",
      status: "Qualified",
      source: "Partner",
      industry: "Manufacturing",
      annualRevenue: 730_000_000,
      rating: "Hot",
      ownerId: "usr_marcus",
      score: 81,
      city: "Istanbul",
      country: "Turkey",
      createdTime: "2026-07-30T12:00:00.000Z",
      converted: false,
    },
    {
      id: "led_clare",
      firstName: "Clare",
      lastName: "Whitfield",
      company: "Northumbria Waterworks",
      title: "Capex Analyst",
      email: "clare.whitfield@nww.co.uk",
      phone: "+44 191 555 0120",
      status: "Contacted",
      source: "Website",
      industry: "Utilities",
      annualRevenue: 305_000_000,
      rating: "Warm",
      ownerId: "usr_jonah",
      score: 57,
      city: "Newcastle",
      country: "United Kingdom",
      createdTime: "2026-09-04T10:11:00.000Z",
      converted: false,
    },
    {
      id: "led_jonas",
      firstName: "Jonas",
      lastName: "Bergström",
      company: "Fjord Pulp",
      title: "Site Director",
      email: "jonas.bergstrom@fjordpulp.se",
      phone: "+46 8 555 0142",
      status: "Unqualified",
      source: "Trade Show",
      industry: "Materials",
      annualRevenue: 22_000_000,
      rating: "Cold",
      ownerId: "usr_jonah",
      score: 19,
      city: "Sundsvall",
      country: "Sweden",
      createdTime: "2026-08-03T14:33:00.000Z",
      converted: false,
    },
    {
      id: "led_amina",
      firstName: "Amina",
      lastName: "El Fassi",
      company: "Atlas Phosphates",
      title: "VP Projects",
      email: "amina.elfassi@atlasphos.ma",
      phone: "+212 5 22 555 090",
      status: "Qualified",
      source: "Outbound",
      industry: "Mining",
      annualRevenue: 540_000_000,
      rating: "Warm",
      ownerId: "usr_marcus",
      score: 73,
      city: "Casablanca",
      country: "Morocco",
      createdTime: "2026-08-16T08:05:00.000Z",
      converted: false,
    },
    {
      id: "led_piotr",
      firstName: "Piotr",
      lastName: "Kamiński",
      company: "Vistula AutoParts",
      title: "Maintenance Lead",
      email: "piotr.kaminski@vistula.auto",
      phone: "+48 22 555 0166",
      status: "Lost Lead",
      source: "Website",
      industry: "Manufacturing",
      annualRevenue: 61_000_000,
      rating: "Cold",
      ownerId: "usr_jonah",
      score: 28,
      city: "Warsaw",
      country: "Poland",
      createdTime: "2026-06-22T11:47:00.000Z",
      converted: false,
    },
  ],
  deals: [
    {
      id: "dea_rhine_chp",
      name: "RhineGrid CHP fleet — Phase 2",
      accountId: "acc_rhinegrid",
      contactId: "con_lena",
      stage: "Closed Won",
      amount: 1_240_000,
      probability: 100,
      closingDate: "2026-08-19T00:00:00.000Z",
      ownerId: "usr_marcus",
      pipeline: "Enterprise",
      nextStep: "Kickoff with delivery on 21 Sep",
      product: "Helios CHP-12",
      leadSource: "Referral",
      createdTime: "2026-03-04T10:00:00.000Z",
      poNumber: "RG-88421",
    },
    {
      id: "dea_oriole",
      name: "Oriole AMS-3 heat reuse",
      accountId: "acc_oriole",
      contactId: "con_iris",
      stage: "Closed Won",
      amount: 860_000,
      probability: 100,
      closingDate: "2026-08-04T00:00:00.000Z",
      ownerId: "usr_theo",
      pipeline: "Enterprise",
      nextStep: "QBR 2 Oct",
      product: "Helios HRX-440",
      leadSource: "Partner",
      createdTime: "2026-01-16T09:00:00.000Z",
      poNumber: "ODC-2219",
    },
    {
      id: "dea_kepler",
      name: "Kepler campus backup CHP",
      accountId: "acc_kepler",
      contactId: "con_hannah",
      stage: "Closed Won",
      amount: 420_000,
      probability: 100,
      closingDate: "2026-06-27T00:00:00.000Z",
      ownerId: "usr_theo",
      pipeline: "Mid-Market",
      nextStep: "Warranty review",
      product: "Helios CHP-12",
      leadSource: "Website",
      createdTime: "2026-02-02T12:00:00.000Z",
      poNumber: "KMT-1044",
    },
    {
      id: "dea_pacific",
      name: "Pacific Foundry HRX line 2",
      accountId: "acc_pacific",
      contactId: "con_owen",
      stage: "Negotiation/Review",
      amount: 980_000,
      probability: 80,
      closingDate: "2026-09-24T00:00:00.000Z",
      ownerId: "usr_marcus",
      pipeline: "Enterprise",
      nextStep: "Legal redlines due Friday",
      product: "Helios HRX-440",
      leadSource: "Trade Show",
      createdTime: "2026-05-11T14:20:00.000Z",
    },
    {
      id: "dea_nordhavn",
      name: "Nordhavn shore-power package",
      accountId: "acc_nordhavn",
      contactId: "con_freja",
      stage: "Proposal/Price Quote",
      amount: 1_450_000,
      probability: 60,
      closingDate: "2026-10-08T00:00:00.000Z",
      ownerId: "usr_priya",
      pipeline: "Enterprise",
      nextStep: "Submit revised TCO model",
      product: "Helios CHP-12 + Pulse",
      leadSource: "Outbound",
      createdTime: "2026-05-20T08:45:00.000Z",
    },
    {
      id: "dea_atlas",
      name: "Atlas kiln waste-heat recovery",
      accountId: "acc_atlas",
      contactId: "con_mateo",
      stage: "Value Proposition",
      amount: 720_000,
      probability: 40,
      closingDate: "2026-10-30T00:00:00.000Z",
      ownerId: "usr_marcus",
      pipeline: "Enterprise",
      nextStep: "On-site heat mapping 18 Sep",
      product: "Helios HRX-440",
      leadSource: "Partner",
      createdTime: "2026-04-02T09:30:00.000Z",
    },
    {
      id: "dea_vossmann",
      name: "Vossmann cold-chain energy",
      accountId: "acc_vossmann",
      contactId: "con_annika",
      stage: "Negotiation/Review",
      amount: 465_000,
      probability: 80,
      closingDate: "2026-09-18T00:00:00.000Z",
      ownerId: "usr_priya",
      pipeline: "Mid-Market",
      nextStep: "CFO sign-off call",
      product: "Helios Pulse + HRX-220",
      leadSource: "Referral",
      createdTime: "2026-06-12T11:00:00.000Z",
    },
    {
      id: "dea_fenwick",
      name: "Fenwick furnace recapture",
      accountId: "acc_fenwick",
      contactId: "con_luc",
      stage: "Proposal/Price Quote",
      amount: 310_000,
      probability: 55,
      closingDate: "2026-10-02T00:00:00.000Z",
      ownerId: "usr_priya",
      pipeline: "Mid-Market",
      nextStep: "Send bilingual quote pack",
      product: "Helios HRX-220",
      leadSource: "Website",
      createdTime: "2026-07-24T13:15:00.000Z",
    },
    {
      id: "dea_lumen",
      name: "Lumen traction substations",
      accountId: "acc_lumen",
      contactId: "con_callum",
      stage: "Needs Analysis",
      amount: 540_000,
      probability: 20,
      closingDate: "2026-11-14T00:00:00.000Z",
      ownerId: "usr_priya",
      pipeline: "Mid-Market",
      nextStep: "Discovery workshop 16 Sep",
      product: "Helios HRX-440",
      leadSource: "Outbound",
      createdTime: "2026-07-06T10:00:00.000Z",
    },
    {
      id: "dea_sable",
      name: "Sable 24MW plant microgrid",
      accountId: "acc_sable",
      contactId: "con_thabo",
      stage: "Qualification",
      amount: 1_100_000,
      probability: 10,
      closingDate: "2026-12-11T00:00:00.000Z",
      ownerId: "usr_marcus",
      pipeline: "Enterprise",
      nextStep: "Confirm budget holder",
      product: "Helios CHP-12 fleet",
      leadSource: "Partner",
      createdTime: "2026-06-01T07:40:00.000Z",
    },
    {
      id: "dea_pulse",
      name: "RhineGrid Pulse monitoring",
      accountId: "acc_rhinegrid",
      contactId: "con_stefan",
      stage: "Value Proposition",
      amount: 180_000,
      probability: 40,
      closingDate: "2026-10-16T00:00:00.000Z",
      ownerId: "usr_theo",
      pipeline: "Mid-Market",
      nextStep: "Security questionnaire",
      product: "Helios Pulse (SaaS)",
      leadSource: "Referral",
      createdTime: "2026-08-08T09:10:00.000Z",
    },
    {
      id: "dea_sable_lost",
      name: "Sable diesel displacement (pilot)",
      accountId: "acc_sable",
      contactId: "con_thabo",
      stage: "Closed Lost",
      amount: 190_000,
      probability: 0,
      closingDate: "2026-07-15T00:00:00.000Z",
      ownerId: "usr_marcus",
      pipeline: "Enterprise",
      nextStep: "Re-engage in FY27 budget",
      product: "Helios CHP-12",
      leadSource: "Outbound",
      createdTime: "2026-03-18T08:00:00.000Z",
      lostReason: "Deferred — capex freeze on pilot sites",
    },
  ],
  activities: [
    {
      id: "act_01",
      subject: "Legal redline review — Pacific Foundry",
      type: "Task",
      status: "In Progress",
      dueDate: "2026-09-12T16:00:00.000Z",
      ownerId: "usr_marcus",
      relatedModule: "Deals",
      relatedId: "dea_pacific",
      relatedName: "Pacific Foundry HRX line 2",
      notes: "Procurement wants liability cap at 12 months of fees.",
    },
    {
      id: "act_02",
      subject: "CFO sign-off — Vossmann",
      type: "Call",
      status: "Not Started",
      dueDate: "2026-09-11T09:30:00.000Z",
      ownerId: "usr_priya",
      relatedModule: "Deals",
      relatedId: "dea_vossmann",
      relatedName: "Vossmann cold-chain energy",
      notes: "Walk the 4.2-year payback vs their 5-year hurdle.",
    },
    {
      id: "act_03",
      subject: "Discovery workshop — Lumen Rail",
      type: "Meeting",
      status: "Not Started",
      dueDate: "2026-09-16T13:00:00.000Z",
      ownerId: "usr_priya",
      relatedModule: "Deals",
      relatedId: "dea_lumen",
      relatedName: "Lumen traction substations",
      notes: "Bring Amira for load-profile modelling.",
    },
    {
      id: "act_04",
      subject: "Heat mapping on-site — Atlas",
      type: "Meeting",
      status: "Not Started",
      dueDate: "2026-09-18T08:00:00.000Z",
      ownerId: "usr_amira",
      relatedModule: "Deals",
      relatedId: "dea_atlas",
      relatedName: "Atlas kiln waste-heat recovery",
      notes: "Need kiln #2 downtime window from Mateo.",
    },
    {
      id: "act_05",
      subject: "Follow-up with Sabine Keller",
      type: "Call",
      status: "Not Started",
      dueDate: "2026-09-10T15:00:00.000Z",
      ownerId: "usr_jonah",
      relatedModule: "Leads",
      relatedId: "led_sabine",
      relatedName: "Sabine Keller",
      notes: "She requested CHP reference in DACH utilities.",
    },
    {
      id: "act_06",
      subject: "Send bilingual quote — Fenwick",
      type: "Task",
      status: "In Progress",
      dueDate: "2026-09-11T17:00:00.000Z",
      ownerId: "usr_priya",
      relatedModule: "Deals",
      relatedId: "dea_fenwick",
      relatedName: "Fenwick furnace recapture",
      notes: "FR/EN pack, include ESG bond language.",
    },
    {
      id: "act_07",
      subject: "Nordhavn TCO revision",
      type: "Task",
      status: "Not Started",
      dueDate: "2026-09-13T12:00:00.000Z",
      ownerId: "usr_priya",
      relatedModule: "Deals",
      relatedId: "dea_nordhavn",
      relatedName: "Nordhavn shore-power package",
      notes: "Include EU shore-power subsidy stacking.",
    },
    {
      id: "act_08",
      subject: "QBR prep — Oriole",
      type: "Task",
      status: "Not Started",
      dueDate: "2026-09-25T10:00:00.000Z",
      ownerId: "usr_theo",
      relatedModule: "Accounts",
      relatedId: "acc_oriole",
      relatedName: "Oriole Data Centers",
      notes: "Uptime and recovered MWh dashboard.",
    },
    {
      id: "act_09",
      subject: "Intro call — Inès Bernard",
      type: "Call",
      status: "Completed",
      dueDate: "2026-09-02T11:00:00.000Z",
      ownerId: "usr_priya",
      relatedModule: "Leads",
      relatedId: "led_ines",
      relatedName: "Inès Bernard",
      notes: "Clean-room HVAC heat recovery. Budget in Oct.",
    },
    {
      id: "act_10",
      subject: "Pacific technical deep-dive",
      type: "Meeting",
      status: "Completed",
      dueDate: "2026-09-04T18:00:00.000Z",
      ownerId: "usr_amira",
      relatedModule: "Deals",
      relatedId: "dea_pacific",
      relatedName: "Pacific Foundry HRX line 2",
      notes: "Validated 14-month payback at $62/MWh.",
    },
    {
      id: "act_11",
      subject: "Vossmann site walk",
      type: "Meeting",
      status: "Completed",
      dueDate: "2026-08-27T09:00:00.000Z",
      ownerId: "usr_priya",
      relatedModule: "Deals",
      relatedId: "dea_vossmann",
      relatedName: "Vossmann cold-chain energy",
      notes: "Compressor hall is the priority load.",
    },
    {
      id: "act_12",
      subject: "Qualify Sable budget holder",
      type: "Call",
      status: "Deferred",
      dueDate: "2026-09-05T08:00:00.000Z",
      ownerId: "usr_marcus",
      relatedModule: "Deals",
      relatedId: "dea_sable",
      relatedName: "Sable 24MW plant microgrid",
      notes: "Thabo travelling. Retry next week.",
    },
    {
      id: "act_13",
      subject: "Security questionnaire — Pulse",
      type: "Task",
      status: "In Progress",
      dueDate: "2026-09-15T16:00:00.000Z",
      ownerId: "usr_theo",
      relatedModule: "Deals",
      relatedId: "dea_pulse",
      relatedName: "RhineGrid Pulse monitoring",
      notes: "ISO 27001 pack already in Zoho WorkDrive.",
    },
    {
      id: "act_14",
      subject: "Partner intro — Anatolia Steel",
      type: "Call",
      status: "Completed",
      dueDate: "2026-08-19T13:00:00.000Z",
      ownerId: "usr_marcus",
      relatedModule: "Leads",
      relatedId: "led_harun",
      relatedName: "Harun Yılmaz",
      notes: "Local partner EgeEnerji can install.",
    },
  ],
  notes: [
    {
      id: "note_01",
      module: "Deals",
      recordId: "dea_pacific",
      authorId: "usr_marcus",
      body: "Board paper circulated. Owen confirmed they will not re-bid if we hold price and move delivery to Q1 2027 for line 3.",
      createdTime: "2026-09-08T19:12:00.000Z",
    },
    {
      id: "note_02",
      module: "Deals",
      recordId: "dea_vossmann",
      authorId: "usr_priya",
      body: "Annika wants the capex in this fiscal year. If legal slips past 30 Sep they lose the accelerated depreciation.",
      createdTime: "2026-09-07T08:44:00.000Z",
    },
    {
      id: "note_03",
      module: "Leads",
      recordId: "led_sabine",
      authorId: "usr_jonah",
      body: "Came in through the CHP calculator on helios.ind/utilities. Score 92 from scoring rule 'Hot inbound utilities'.",
      createdTime: "2026-08-28T07:20:00.000Z",
    },
    {
      id: "note_04",
      module: "Accounts",
      recordId: "acc_rhinegrid",
      authorId: "usr_elena",
      body: "Strategic account. Elena sponsoring executive alignment with their COO in October.",
      createdTime: "2026-08-20T10:00:00.000Z",
    },
    {
      id: "note_05",
      module: "Deals",
      recordId: "dea_nordhavn",
      authorId: "usr_amira",
      body: "Shore-power load profile is peaky. Recommend CHP-12 + 2 MWh buffer, not a single oversized unit.",
      createdTime: "2026-09-03T15:28:00.000Z",
    },
  ],
  workflows: [
    {
      id: "wf_01",
      name: "Hot inbound utilities → assign SDR + score",
      module: "Leads",
      trigger: "On create",
      condition: "Lead_Source = Website AND Industry = Utilities AND Annual_Revenue > 100000000",
      actions: [
        "Assign to Jonah Hale",
        "Set Rating = Hot",
        "Add 25 to Lead_Score",
        "Create Call 'Same-day follow-up'",
        "Notify Elena Voss",
      ],
      status: "Active",
      lastRun: "2026-08-28T07:14:12.000Z",
      runs: 38,
    },
    {
      id: "wf_02",
      name: "Deal entering Negotiation → legal checklist",
      module: "Deals",
      trigger: "On edit · Stage",
      condition: "Stage moves to Negotiation/Review",
      actions: [
        "Create Task 'Legal redline review' due in 2 days",
        "Tag Deal 'Legal-review'",
        "Notify owner + VP Sales",
      ],
      status: "Active",
      lastRun: "2026-09-06T11:02:00.000Z",
      runs: 11,
    },
    {
      id: "wf_03",
      name: "Closed Won → kickoff + CSM handoff",
      module: "Deals",
      trigger: "On edit · Stage",
      condition: "Stage = Closed Won AND PO_Number is not empty",
      actions: [
        "Convert related Lead if still open",
        "Create Task for Theo Brandt 'Customer kickoff'",
        "Webhook POST to Helios ERP /orders",
        "Send Deluge mail template 'Win announcement'",
      ],
      status: "Active",
      lastRun: "2026-08-19T16:41:00.000Z",
      runs: 9,
    },
    {
      id: "wf_04",
      name: "Stale proposal after 14 days",
      module: "Deals",
      trigger: "Time-based",
      condition: "Stage = Proposal/Price Quote AND Modified_Time older than 14 days",
      actions: ["Create Task 'Re-engage buyer'", "Drop probability by 10", "Slack #revenue-ops"],
      status: "Active",
      lastRun: "2026-09-09T06:00:00.000Z",
      runs: 4,
    },
    {
      id: "wf_05",
      name: "Lead conversion writes Account 360",
      module: "Leads",
      trigger: "On convert",
      condition: "Always",
      actions: [
        "Create Account + Contact + Deal",
        "Copy custom field Plant_Count",
        "Attach Blueprint 'Enterprise Pipeline'",
      ],
      status: "Active",
      lastRun: "2026-08-04T12:10:00.000Z",
      runs: 17,
    },
    {
      id: "wf_06",
      name: "Discount > 12% requires VP approval",
      module: "Deals",
      trigger: "Blueprint transition",
      condition: "Discount > 12 AND Stage → Closed Won",
      actions: ["Pause Blueprint", "Create Approval 'VP discount'", "Email Elena Voss"],
      status: "Active",
      lastRun: "2026-07-22T09:18:00.000Z",
      runs: 3,
    },
  ],
  syncLog: [
    {
      id: "sync_01",
      at: "2026-09-10T13:42:11.000Z",
      module: "Deals",
      action: "GET",
      endpoint: "GET /crm/v8/Deals",
      records: 12,
      status: "Synced",
      latencyMs: 184,
    },
    {
      id: "sync_02",
      at: "2026-09-10T13:42:12.000Z",
      module: "Leads",
      action: "GET",
      endpoint: "GET /crm/v8/Leads",
      records: 10,
      status: "Synced",
      latencyMs: 151,
    },
    {
      id: "sync_03",
      at: "2026-09-10T12:10:04.000Z",
      module: "Contacts",
      action: "PUT",
      endpoint: "PUT /crm/v8/Contacts/3652397000000804411",
      records: 1,
      status: "Synced",
      latencyMs: 96,
    },
    {
      id: "sync_04",
      at: "2026-09-10T11:04:22.000Z",
      module: "Deals",
      action: "COQL",
      endpoint: "POST /crm/v8/coql",
      records: 5,
      status: "Synced",
      latencyMs: 210,
    },
    {
      id: "sync_05",
      at: "2026-09-10T09:00:01.000Z",
      module: "Watch",
      action: "WATCH",
      endpoint: "POST /crm/v8/actions/watch",
      records: 0,
      status: "Synced",
      latencyMs: 72,
    },
    {
      id: "sync_06",
      at: "2026-09-09T18:22:47.000Z",
      module: "Leads",
      action: "CONVERT",
      endpoint: "POST /crm/v8/Leads/{id}/actions/convert",
      records: 1,
      status: "Synced",
      latencyMs: 340,
    },
    {
      id: "sync_07",
      at: "2026-09-09T16:01:09.000Z",
      module: "Accounts",
      action: "GET",
      endpoint: "GET /crm/v8/Accounts",
      records: 10,
      status: "Retrying",
      latencyMs: 2400,
    },
    {
      id: "sync_08",
      at: "2026-09-09T08:13:55.000Z",
      module: "Activities",
      action: "POST",
      endpoint: "POST /crm/v8/Tasks",
      records: 1,
      status: "Failed",
      latencyMs: 0,
    },
  ],
}

const TOUCHPOINTS: Record<string, LeadTouchpoints> = {
  led_sabine: {
    websiteSessions: 5,
    usedChpCalculator: true,
    emailOpens: 4,
    emailClicks: 2,
  },
  led_rafael: {
    websiteSessions: 3,
    usedChpCalculator: false,
    emailOpens: 2,
    emailClicks: 1,
  },
  led_mei: {
    websiteSessions: 2,
    usedChpCalculator: false,
    emailOpens: 1,
    emailClicks: 0,
  },
  led_dario: {
    websiteSessions: 1,
    usedChpCalculator: false,
    emailOpens: 0,
    emailClicks: 0,
  },
  led_ines: {
    websiteSessions: 4,
    usedChpCalculator: false,
    emailOpens: 3,
    emailClicks: 1,
  },
  led_harun: {
    websiteSessions: 4,
    usedChpCalculator: false,
    emailOpens: 2,
    emailClicks: 1,
  },
  led_clare: {
    websiteSessions: 2,
    usedChpCalculator: true,
    emailOpens: 1,
    emailClicks: 0,
  },
  led_jonas: {
    websiteSessions: 1,
    usedChpCalculator: false,
    emailOpens: 0,
    emailClicks: 0,
  },
  led_amina: {
    websiteSessions: 3,
    usedChpCalculator: false,
    emailOpens: 2,
    emailClicks: 1,
  },
  led_piotr: {
    websiteSessions: 1,
    usedChpCalculator: false,
    emailOpens: 0,
    emailClicks: 0,
  },
}

export const seed = {
  ...rawSeed,
  disabledScoringRuleIds: [] as string[],
  leads: rawSeed.leads.map((lead) => ({
    ...lead,
    touchpoints: TOUCHPOINTS[lead.id] ?? EMPTY_TOUCHPOINTS,
  })),
} as CrmState
